version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redisRepository:6379
    volumes:
      - ./.env:/app/.env
      - .:/app
      - /app/tmp
    networks:
      - mynetwork

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:


